In [2]:
import numpy as np
arr=np.array([1,2,3,4,5], ndmin=2),
print(arr)
x=np.zeros([2,2])
print(x)
y=np.ones([2,2])
print(y)
z=np.arange(1,10,2)
print(z)
a=np.linspace(1,100,9)
print(a)
r=10+np.random.rand(5,5)*10
print(r)


(array([[1, 2, 3, 4, 5]]),)
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 3 5 7 9]
[  1.     13.375  25.75   38.125  50.5    62.875  75.25   87.625 100.   ]
[[17.00260431 11.14014928 12.27827157 13.2714209  17.32171948]
 [14.51567732 15.81210078 10.14720102 19.9710961  10.31013852]
 [11.56319317 18.51245266 16.13361399 17.43158582 12.85088665]
 [16.94163923 11.66729537 10.09092306 10.43313591 18.6113293 ]
 [11.88792009 11.95291822 19.67575175 19.3877367  16.04243345]]


In [3]:
#Create a 5x5 matrix with values 1 to 25 and reshape it into a 25x1 array.
arr=np.arange(25).reshape(5,5)
arr1=arr.reshape(25,1)
print(arr)
print('='*50)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [ ]:
#Create a 10x10 matrix filled with random integers between 10 and 100. Then replace all even numbers with -1.
x=np.random.randint(10,100,(10,10))
x[x%2==0]=-1
print(x)


[[-1 -1 -1 53 53 67 43 -1 -1 23]
 [-1 69 61 21 -1 -1 79 -1 -1 99]
 [37 -1 -1 -1 21 65 -1 59 69 97]
 [-1 37 -1 35 43 -1 17 77 63 -1]
 [-1 83 59 43 -1 -1 -1 19 -1 -1]
 [79 -1 11 -1 -1 71 -1 17 25 -1]
 [-1 -1 97 87 -1 -1 27 -1 -1 61]
 [19 45 23 -1 81 -1 -1 23 55 45]
 [-1 -1 -1 -1 -1 -1 55 -1 -1 -1]
 [-1 -1 -1 -1 27 -1 -1 51 83 -1]]


In [ ]:
#Generate a 3D array of shape (3, 3, 3) with random values and normalize it (scale between 0 and 1).
x=np.random.random((3,3,3))
normalized=(x-np.min(x))/(np.max(x)-np.min(x))
print(normalized)


[[[0.61050341 0.4395392  0.90122708]
  [0.10287951 0.71556615 0.52463995]
  [0.2452249  0.91195521 0.74065953]]

 [[0.10084862 0.         0.40000298]
  [0.72392649 0.80354524 0.03458485]
  [0.09058467 0.84558522 0.71561693]]

 [[0.58676006 0.99034796 0.29065673]
  [0.57539577 0.59556508 0.13515858]
  [1.         0.79675732 0.22421195]]]


In [ ]:
x=np.random.random((3,3,3))
normalized=(x-np.min(x))/(np.max(x)-np.min(x))
print(normalized)

[[[0.32645576 0.97529508 0.51935414]
  [0.38704196 0.43662615 0.65622997]
  [0.39914424 0.76622688 0.68815756]]

 [[0.38144852 0.11940477 0.65606065]
  [0.68416818 0.16895871 0.392914  ]
  [1.         0.16927512 0.49037796]]

 [[0.53930742 0.58834006 0.61679632]
  [0.29058841 0.6276891  0.        ]
  [0.93106198 0.89157559 0.60070569]]]


In [ ]:
#Create an array of 20 linearly spaced numbers between -1 and 1, and then reverse the order.
x=np.linspace(-1,1,20)[::-1]
print(x)


[ 1.          0.89473684  0.78947368  0.68421053  0.57894737  0.47368421
  0.36842105  0.26315789  0.15789474  0.05263158 -0.05263158 -0.15789474
 -0.26315789 -0.36842105 -0.47368421 -0.57894737 -0.68421053 -0.78947368
 -0.89473684 -1.        ]


In [ ]:
#Create a 2D array with random integers and sort it along the columns and then along the rows.
x=np.random.randint(1,101,(5,5))
print(x)
y=np.sort(x,axis=0) #Vertical sorting
print("="*50)
print(y)
print("="*50)
z=np.sort(x,axis=1) #Vertical Sorting
print(z)

[[ 94  77  25  56  55]
 [ 70  58  32  21  92]
 [ 52  71   6  58  90]
 [ 72  74  95  80 100]
 [ 49  32  27  50  40]]
[[ 49  32   6  21  40]
 [ 52  58  25  50  55]
 [ 70  71  27  56  90]
 [ 72  74  32  58  92]
 [ 94  77  95  80 100]]
[[ 25  55  56  77  94]
 [ 21  32  58  70  92]
 [  6  52  58  71  90]
 [ 72  74  80  95 100]
 [ 27  32  40  49  50]]


In [ ]:
#Calculate the mean, median, variance, and standard deviation of a random 1D array with 1000 elements.
import numpy as z
x=10+(z.random.randn(1000)*10)  #creating a random array with 1000 elements
print("Mean: ",z.mean(x))       #finding mean
print("Median :",z.median(x))   #finding median
print("Variance :",z.var(x))    #finding variance
print("Standard Variation :",z.std(x)) #finding standard variation)))

Mean:  9.962952334820956
Median : 9.418933894372223
Variance : 93.93788970861517
Standard Variation : 9.692156091841236


In [ ]:
#Find the 25th, 50th, and 75th percentiles of an array with random values.
import numpy as n
x=n.random.randn((100))
new=x.reshape(10,10)
per25=n.percentile(new,25,axis=None,keepdims=True ) #n.percentile(arr,percentileth,axis,keepdims=to keep the dimension pf percentile same as input array)
print("25 percentile :",per25)
print('='*50)
per50=n.percentile(new,50,axis=0,keepdims=True)  #axis =0 mean vertical
print('50 percentile :',per50)
print('='*50)
print("75 percentile :",n.percentile(new,75,axis=1,keepdims=True)) #axis=1 means at horizontal axis


25 percentile : [[-0.79848702]]
50 percentile : [[ 0.03590091  0.36763353  0.35323445  0.14896946  0.35386312 -0.63426658
  -0.55849095 -0.79347384 -0.16334982 -0.46693337]]
75 percentile : [[ 0.05362568]
 [ 0.33407707]
 [ 0.24318905]
 [ 0.71038604]
 [ 0.18671035]
 [ 0.15235356]
 [ 0.7869183 ]
 [ 0.52732406]
 [-0.28624679]
 [ 1.54706907]]


In [ ]:
import numpy as np
x=np.random.randint(1,26,(5,5))
print(x)
print("="*50)
b=x[2:4,1:3]
print(b)
print("="*50)
c=b[0:1,0:1]
print(c)
c[0:1,0:1]=77
print(c)


[[11 17  5 25 24]
 [ 9  2 14 18 23]
 [12 22 15 21  4]
 [19 17 25 25 20]
 [15  2 24  2 17]]
[[22 15]
 [17 25]]
[[22]]
[[77]]


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1, 26, size=(5, 5)))
print(df)

    0   1   2   3   4
0   6   6   4   4  13
1  12  25  16  10  11
2  12  21  16  18   3
3  23  19   1   6  22
4  11   7   5   1   7


In [ ]:
data=[10,20,30,40,50]
series_from_list=pd.Series(data)
print(series_from_list)
print("="*50)
print(type(series_from_list))
series1=pd.Series(np.array([1,2,3,4,5,6]))
print("="*50)
print(series1)
print("="*50)
custom_index = pd.Series(data=data, index=["A", "B", "C", "D", "E"])
print(custom_index)
print(custom_index.index[0])

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32
A    10
B    20
C    30
D    40
E    50
dtype: int64
A


In [ ]:
atposition2=custom_index["A"]
print(atposition2)

10


In [ ]:
slice_series=series_from_list[1:4]
defprint("Slice of series from list :",slice_series)

Slice of series from list : 1    20
2    30
3    40
dtype: int64


In [ ]:
def col_to_series(series,column):
    return seires[column].tolist()
data={"Name":["Amir","Saif","Younus"],
    "Age":["25","30","35"]}
df=pd.DataFrame(data=data)
print(df)
print("="*50)
print(col_to_series(df,"Name"))


     Name Age
0    Amir  25
1    Saif  30
2  Younus  35
['Amir', 'Saif', 'Younus']


In [ ]:
import pandas as pd

def add_new_column(df, column_name, values):
    if column_name not in df.columns:
        df[column_name] = values
    else:
        raise ValueError(f"Column '{column_name}' already exists in DataFrame")
    return df

data = {"Name": ["Amir", "Saif", "Younus"],
        "Age": ["25", "30", "35"]}
df = pd.DataFrame(data=data)

print("Original DataFrame:")
print(df)
print("="*50)

new_column_name = "Country"
new_column_values = ["Pakistan", "India", "Bangladesh"]

df = add_new_column(df, new_column_name, new_column_values)

print("Updated DataFrame:")
print(df)

Original DataFrame:
     Name Age
0    Amir  25
1    Saif  30
2  Younus  35
Updated DataFrame:
     Name Age     Country
0    Amir  25    Pakistan
1    Saif  30       India
2  Younus  35  Bangladesh


In [ ]:
data_list=[["Saif","24","Lahore"],["Amir","24","Islamabad"],["Ali","24","Rawalpindi"]]
df=pd.DataFrame(data_list,columns=["Name","Age","City"])
print("Dta frame created from lists of lists: ")
print(df)
print("="*50)
print(df.loc[2])

Dta frame created from lists of lists: 
   Name Age        City
0  Saif  24      Lahore
1  Amir  24   Islamabad
2   Ali  24  Rawalpindi
Name           Ali
Age             24
City    Rawalpindi
Name: 2, dtype: object


In [ ]:
dict={"a":1,"b":2}
res_dict={1:"a",2:"b"}

Empty DataFrame
Columns: []
Index: []


In [ ]:
def inverted_dict_keys_values(input_dict):
    return {v: k for k, v in input_dict.items()}
dict = {"a": 1, "b": 2}
res_dict=inverted_dict_keys_values(dict)
print("="*50)
print("Inverted Dictionary is: ",res_dict)
print("="*50)  

Inverted Dictionary is:  {1: 'a', 2: 'b'}


In [ ]:
#input="aabcccccaaa"
#output="a2b1c5a3"
def compress_string(s): #defining the function
    compressed = []     #defining the dict
    count = 1           #starting the count
    for i in range(1, len(s)):  #loop
        if s[i] == s[i-1]:      #if the next element is same as previous one
            count += 1          #count increment by 1
        else:
            compressed.append(s[i-1] + str(count)) #append the pervious element by count
            count = 1                              #resetting count to 1
    compressed.append(s[-1] + str(count))          #for last element and string count 
    return ''.join(compressed)                     #join the elements by .join
Input_string= input("Enter a string: ")
print("iNPUT sTRING :", Input_string)
Output_str = compress_string(Input_string)
print("CompresseD String:", Output_str)

iNPUT sTRING : aabbbccc
CompresseD String: a2b3c3


In [ ]:
#Create a 3D array and extract a specific pattern of elements using advanced indexing techniques. For example, extract elements from alternating rows and columns in a non-trivial manner.
import numpy as np 
x=np.arange(27).reshape(3,3,3)
print(x)
a=x[: ,::2 ,::2]
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  2]
  [ 6  8]]

 [[ 9 11]
  [15 17]]

 [[18 20]
  [24 26]]]


In [ ]:
#Create a masked array where specific values are hidden based on a condition (e.g., all negative values). Perform operations on this masked array while ignoring the masked elements.
x=np.arange(27).reshape(3,3,3)
masked_array=np.ma.masked_where(x==0,x)
mean_of_masked_array=masked_array.mean()
print(masked_array)
print("="*50)
print(mean_of_masked_array)


[[[-- 1 2]
  [3 4 5]
  [6 7 8]]

 [[9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
13.5


In [ ]:
#Implement a function that performs a vectorized operation to calculate the Manhattan distance between points in an N-dimensional space, using NumPy arrays.

def manhattan_distance(a,b):
    return np.sum(np.abs(a-b),axis=-1)
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])
distance1=manhattan_distance(c,d)  
print(distance1)

[18 18]


In [ ]:
#Generate a signal composed of multiple sine waves with different frequencies. Use NumPy’s Fast Fourier Transform (FFT) to analyze the frequency components of the signal.
t=np.linspace(0,1,500)
print(t)
x=np.sin(2*np.pi*5*t)+np.sin(2*np.pi*10*t)
fft1=np.fft.fft(x)
print("="*50)
print(fft1)
print("="*50)
freq=np.fft.fftfreq(len(x),d=t[1]-t[0])
print(freq)

[0.         0.00200401 0.00400802 0.00601202 0.00801603 0.01002004
 0.01202405 0.01402806 0.01603206 0.01803607 0.02004008 0.02204409
 0.0240481  0.0260521  0.02805611 0.03006012 0.03206413 0.03406814
 0.03607214 0.03807615 0.04008016 0.04208417 0.04408818 0.04609218
 0.04809619 0.0501002  0.05210421 0.05410822 0.05611222 0.05811623
 0.06012024 0.06212425 0.06412826 0.06613226 0.06813627 0.07014028
 0.07214429 0.0741483  0.0761523  0.07815631 0.08016032 0.08216433
 0.08416834 0.08617234 0.08817635 0.09018036 0.09218437 0.09418838
 0.09619238 0.09819639 0.1002004  0.10220441 0.10420842 0.10621242
 0.10821643 0.11022044 0.11222445 0.11422846 0.11623246 0.11823647
 0.12024048 0.12224449 0.1242485  0.12625251 0.12825651 0.13026052
 0.13226453 0.13426854 0.13627255 0.13827655 0.14028056 0.14228457
 0.14428858 0.14629259 0.14829659 0.1503006  0.15230461 0.15430862
 0.15631263 0.15831663 0.16032064 0.16232465 0.16432866 0.16633267
 0.16833667 0.17034068 0.17234469 0.1743487  0.17635271 0.1783

In [ ]:
import pandas as pd
import numpy as np
x=pd.Series([1,2,3,4,5],index=["b","a","d","c","e"])
print(x)
print("="*50)
print(x.sort_index())
print("="*50)
print(x.sort_values())
z=pd.DataFrame(x)
print(z)

b    1
a    2
d    3
c    4
e    5
dtype: int64
a    2
b    1
c    4
d    3
e    5
dtype: int64
b    1
a    2
d    3
c    4
e    5
dtype: int64
   0
b  1
a  2
d  3
c  4
e  5


In [ ]:
df=pd.read_csv("ny_weather.csv")

In [ ]:
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016         38.0      23.0      52.0                 30.03   
1  1/2/2016         36.0      18.0      46.0                 30.02   
2  1/3/2016          NaN       NaN      47.0                 29.86   
3  1/6/2016         33.0       NaN      35.0                   NaN   
4  1/7/2016         39.0      11.0      33.0                 30.28   

   VisibilityMiles  WindSpeedMPH   Event  
0             10.0           8.0    Rain  
1             10.0           7.0   Sunny  
2             10.0           8.0    Snow  
3             10.0           4.0    Rain  
4             10.0           2.0  Cloudy

In [ ]:
df.head(15)

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016         38.0      23.0      52.0                 30.03   
1    1/2/2016         36.0      18.0      46.0                 30.02   
2    1/3/2016          NaN       NaN      47.0                 29.86   
3    1/6/2016         33.0       NaN      35.0                   NaN   
4    1/7/2016         39.0      11.0      33.0                 30.28   
5    1/8/2016         39.0      29.0       NaN                 30.20   
6    1/9/2016         44.0      38.0      77.0                 30.16   
7   1/10/2016          NaN      46.0       NaN                   NaN   
8   1/11/2016         33.0       8.0      37.0                 29.92   
9   1/12/2016         35.0       NaN      53.0                 29.85   
10  1/13/2016         26.0       4.0       NaN                 29.94   
11  1/14/2016          NaN      12.0      47.0                   NaN   
12  1/17/2016         36.0      23.0      66.0                 29.78   
13  1/18/2016         25.0       6.0      53.0                 29.83   

    VisibilityMiles  WindSpeedMPH   Event  
0              10.0           8.0    Rain  
1              10.0           7.0   Sunny  
2              10.0           8.0    Snow  
3              10.0           4.0    Rain  
4              10.0           2.0  Cloudy  
5              10.0           4.0   Sunny  
6               NaN           8.0     NaN  
7               4.0           NaN    Snow  
8              10.0           NaN     NaN  
9              10.0           6.0     NaN  
10             10.0          10.0    Rain  
11              NaN           NaN    Rain  
12              8.0           6.0    Snow  
13              9.0           NaN   Sunny

In [ ]:
df.tail()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
9   1/12/2016         35.0       NaN      53.0                 29.85   
10  1/13/2016         26.0       4.0       NaN                 29.94   
11  1/14/2016          NaN      12.0      47.0                   NaN   
12  1/17/2016         36.0      23.0      66.0                 29.78   
13  1/18/2016         25.0       6.0      53.0                 29.83   

    VisibilityMiles  WindSpeedMPH  Event  
9              10.0           6.0    NaN  
10             10.0          10.0   Rain  
11              NaN           NaN   Rain  
12              8.0           6.0   Snow  
13              9.0           NaN  Sunny

In [ ]:
df.columns

Index(['Date', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'Event'],
      dtype='object')

In [ ]:
df.shape

(14, 8)

In [ ]:
df.loc[6:11,["Temperature","Humidity","Event"]]

Temperature  Humidity Event
6          44.0      77.0   NaN
7           NaN       NaN  Snow
8          33.0      37.0   NaN
9          35.0      53.0   NaN
10         26.0       NaN  Rain
11          NaN      47.0  Rain

In [ ]:
df.ndim

2

In [ ]:
df.loc[:]

Date  Temperature  DewPoint   Humidity  Sea Level PressureIn  \
0    1/1/2016    38.000000      23.0  52.000000             30.030000   
1    1/2/2016    36.000000      18.0  46.000000             30.020000   
2    1/3/2016    38.166667      27.5  47.000000             29.860000   
3    1/6/2016    33.000000      27.5  35.000000             30.091667   
4    1/7/2016    39.000000      11.0  33.000000             30.280000   
5    1/8/2016    39.000000      29.0  48.333333             30.200000   
6    1/9/2016    44.000000      38.0  77.000000             30.160000   
7   1/10/2016    38.166667      46.0  48.333333             30.091667   
14  1/18/2018    40.000000      10.0  30.000000             20.000000   

    VisibilityMiles  WindSpeedMPH  
0         10.000000      8.000000  
1         10.000000      7.000000  
2         10.000000      8.000000  
3         10.000000      4.000000  
4         10.000000      2.000000  
5         10.000000      4.000000  
6          9.142857      8.000000  
7          4.000000      5.857143  
14        50.700000     10.000000

In [ ]:
df.loc[6:11]

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
6    1/9/2016         44.0      38.0      77.0                 30.16   
7   1/10/2016          NaN      46.0       NaN                   NaN   
8   1/11/2016         33.0       8.0      37.0                 29.92   
9   1/12/2016         35.0       NaN      53.0                 29.85   
10  1/13/2016         26.0       4.0       NaN                 29.94   
11  1/14/2016          NaN      12.0      47.0                   NaN   

    VisibilityMiles  WindSpeedMPH Event  
6               NaN           8.0   NaN  
7               4.0           NaN  Snow  
8              10.0           NaN   NaN  
9              10.0           6.0   NaN  
10             10.0          10.0  Rain  
11              NaN           NaN  Rain

In [ ]:
df.loc[df.iloc[:,3]>50] #loc function find the whole dataframe and iloc does bool in the backend

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016         38.0      23.0      52.0                 30.03   
6    1/9/2016         44.0      38.0      77.0                 30.16   
9   1/12/2016         35.0       NaN      53.0                 29.85   
12  1/17/2016         36.0      23.0      66.0                 29.78   
13  1/18/2016         25.0       6.0      53.0                 29.83   

    VisibilityMiles  WindSpeedMPH  Event  
0              10.0           8.0   Rain  
6               NaN           8.0    NaN  
9              10.0           6.0    NaN  
12              8.0           6.0   Snow  
13              9.0           NaN  Sunny

In [ ]:
print(df[df["Humidity"]>50]) #finding rows in which humidity is greater than 50

         Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016         38.0      23.0      52.0                 30.03   
6    1/9/2016         44.0      38.0      77.0                 30.16   
9   1/12/2016         35.0       NaN      53.0                 29.85   
12  1/17/2016         36.0      23.0      66.0                 29.78   
13  1/18/2016         25.0       6.0      53.0                 29.83   

    VisibilityMiles  WindSpeedMPH  Event  
0              10.0           8.0   Rain  
6               NaN           8.0    NaN  
9              10.0           6.0    NaN  
12              8.0           6.0   Snow  
13              9.0           NaN  Sunny  


In [ ]:
values1=np.random.randn(df.shape[0])         #defining an array that is equal to the no of rows of the above dataframe
values2=np.random.randn(len(df)) #arange(len(df)),arange(df.shape[0])
values3=np.arange(df.index.size)
print(values1)
print("="*50)
print(values2)
print("="*50)
print(values3)
print(len(df))

[ 0.52284565  1.69756583 -0.4022049   1.57095849  0.61354271  0.83628229
  1.11497992 -1.65325169]
[-0.78446669  1.5783187  -0.57383151 -0.50729859  1.07220957  1.66253804
  1.2330212  -0.56898205]
[0 1 2 3 4 5 6 7]
8


In [ ]:
df.drop("Event",axis=1,inplace=True) #removing a column,axis =column vertical,inplace means changes will be in same df

In [ ]:
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016    38.000000      23.0      52.0             30.030000   
1  1/2/2016    36.000000      18.0      46.0             30.020000   
2  1/3/2016    38.166667      27.5      47.0             29.860000   
3  1/6/2016    33.000000      27.5      35.0             30.091667   
4  1/7/2016    39.000000      11.0      33.0             30.280000   

   VisibilityMiles  WindSpeedMPH  
0             10.0           8.0  
1             10.0           7.0  
2             10.0           8.0  
3             10.0           4.0  
4             10.0           2.0

In [ ]:
df.loc[14]=["1/18/2018",40.0,10.0,30.0,20.0,50.7,10.0]
df.head(15)

Date  Temperature  DewPoint   Humidity  Sea Level PressureIn  \
0    1/1/2016    38.000000      23.0  52.000000             30.030000   
1    1/2/2016    36.000000      18.0  46.000000             30.020000   
2    1/3/2016    38.166667      27.5  47.000000             29.860000   
3    1/6/2016    33.000000      27.5  35.000000             30.091667   
4    1/7/2016    39.000000      11.0  33.000000             30.280000   
5    1/8/2016    39.000000      29.0  48.333333             30.200000   
6    1/9/2016    44.000000      38.0  77.000000             30.160000   
7   1/10/2016    38.166667      46.0  48.333333             30.091667   
14  1/18/2018    40.000000      10.0  30.000000             20.000000   

    VisibilityMiles  WindSpeedMPH  
0         10.000000      8.000000  
1         10.000000      7.000000  
2         10.000000      8.000000  
3         10.000000      4.000000  
4         10.000000      2.000000  
5         10.000000      4.000000  
6          9.142857      8.000000  
7          4.000000      5.857143  
14        50.700000     10.000000

In [ ]:
df.drop[8,13]     #for removing 3,13 row
df.drop(df.index[8:13],inplace=True)       # for removing the range of rows
df.head

TypeError: 'method' object is not subscriptable

In [ ]:
df.set_index("Date",inplace=True)  #now setting dates as index
df.head()

Temperature  DewPoint  Humidity  Sea Level PressureIn  \
Date                                                              
1/1/2016         38.0      23.0      52.0                 30.03   
1/2/2016         36.0      18.0      46.0                 30.02   
1/3/2016          NaN       NaN      47.0                 29.86   
1/6/2016         33.0       NaN      35.0                   NaN   
1/7/2016         39.0      11.0      33.0                 30.28   

          VisibilityMiles  WindSpeedMPH  
Date                                     
1/1/2016             10.0           8.0  
1/2/2016             10.0           7.0  
1/3/2016             10.0           8.0  
1/6/2016             10.0           4.0  
1/7/2016             10.0           2.0

In [ ]:
df.reset_index(inplace=True) #Undoing the last operation
df.head(8)

level_0  index       Date  Temperature  DewPoint  Humidity  \
0        0      0   1/1/2016         38.0      23.0      52.0   
1        1      1   1/2/2016         36.0      18.0      46.0   
2        2      2   1/3/2016          NaN       NaN      47.0   
3        3      3   1/6/2016         33.0       NaN      35.0   
4        4      4   1/7/2016         39.0      11.0      33.0   
5        5      5   1/8/2016         39.0      29.0       NaN   
6        6      6   1/9/2016         44.0      38.0      77.0   
7        7      7  1/10/2016          NaN      46.0       NaN   

   Sea Level PressureIn  VisibilityMiles  WindSpeedMPH  
0                 30.03             10.0           8.0  
1                 30.02             10.0           7.0  
2                 29.86             10.0           8.0  
3                   NaN             10.0           4.0  
4                 30.28             10.0           2.0  
5                 30.20             10.0           4.0  
6                 30.16              NaN           8.0  
7                   NaN              4.0           NaN

In [ ]:
df.drop(["level_0", "index"], axis=1, inplace=True)
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016         38.0      23.0      52.0                 30.03   
1  1/2/2016         36.0      18.0      46.0                 30.02   
2  1/3/2016          NaN       NaN      47.0                 29.86   
3  1/6/2016         33.0       NaN      35.0                   NaN   
4  1/7/2016         39.0      11.0      33.0                 30.28   

   VisibilityMiles  WindSpeedMPH  
0             10.0           8.0  
1             10.0           7.0  
2             10.0           8.0  
3             10.0           4.0  
4             10.0           2.0

In [ ]:
df.mean(numeric_only=True)

Temperature             38.166667
DewPoint                27.500000
Humidity                48.333333
Sea Level PressureIn    30.091667
VisibilityMiles          9.142857
WindSpeedMPH             5.857143
dtype: float64

In [ ]:
df.fillna(df.mean(numeric_only=True),inplace=True) #filling na values with their meann value
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016    38.000000      23.0      52.0             30.030000   
1  1/2/2016    36.000000      18.0      46.0             30.020000   
2  1/3/2016    38.166667      27.5      47.0             29.860000   
3  1/6/2016    33.000000      27.5      35.0             30.091667   
4  1/7/2016    39.000000      11.0      33.0             30.280000   

   VisibilityMiles  WindSpeedMPH  
0             10.0           8.0  
1             10.0           7.0  
2             10.0           8.0  
3             10.0           4.0  
4             10.0           2.0

In [ ]:
df.dropna(inplace=True)  #drop rows that have na in their rows
df.head(8)
df.assign("Event"=[])

Date  Temperature  DewPoint   Humidity  Sea Level PressureIn  \
0   1/1/2016    38.000000      23.0  52.000000             30.030000   
1   1/2/2016    36.000000      18.0  46.000000             30.020000   
2   1/3/2016    38.166667      27.5  47.000000             29.860000   
3   1/6/2016    33.000000      27.5  35.000000             30.091667   
4   1/7/2016    39.000000      11.0  33.000000             30.280000   
5   1/8/2016    39.000000      29.0  48.333333             30.200000   
6   1/9/2016    44.000000      38.0  77.000000             30.160000   
7  1/10/2016    38.166667      46.0  48.333333             30.091667   

   VisibilityMiles  WindSpeedMPH  
0        10.000000      8.000000  
1        10.000000      7.000000  
2        10.000000      8.000000  
3        10.000000      4.000000  
4        10.000000      2.000000  
5        10.000000      4.000000  
6         9.142857      8.000000  
7         4.000000      5.857143

In [ ]:
df.groupby("WindSpeedMPH")["Temperature"].mean() #like pivot table grouping the one column with respect to the other

WindSpeedMPH
2.000000     39.000000
4.000000     36.000000
5.857143     38.166667
7.000000     36.000000
8.000000     40.055556
10.000000    40.000000
Name: Temperature, dtype: float64

In [ ]:
def miles_to_km(x):
    return x * 1.60934
df["VisibilityMiles"]=df["VisibilityMiles"].apply(miles_to_km)

In [ ]:
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016    38.000000      23.0      52.0             30.030000   
1  1/2/2016    36.000000      18.0      46.0             30.020000   
2  1/3/2016    38.166667      27.5      47.0             29.860000   
3  1/6/2016    33.000000      27.5      35.0             30.091667   
4  1/7/2016    39.000000      11.0      33.0             30.280000   

   VisibilityMiles  WindSpeedMPH  
0          16.0934           8.0  
1          16.0934           7.0  
2          16.0934           8.0  
3          16.0934           4.0  
4          16.0934           2.0

In [ ]:
df["Visibilitykm"]=df["VisibilityMiles"].apply(lambda x:x*1.60934)
df.head()

Date  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016    38.000000      23.0      52.0             30.030000   
1  1/2/2016    36.000000      18.0      46.0             30.020000   
2  1/3/2016    38.166667      27.5      47.0             29.860000   
3  1/6/2016    33.000000      27.5      35.0             30.091667   
4  1/7/2016    39.000000      11.0      33.0             30.280000   

   VisibilityMiles  WindSpeedMPH  Visibilitykm  
0        25.899752           8.0     41.681507  
1        25.899752           7.0     41.681507  
2        25.899752           8.0     41.681507  
3        25.899752           4.0     41.681507  
4        25.899752           2.0     41.681507

In [ ]:
Max=lambda x,y: x if (x>y) else y
print(Max(1,2))

2


In [ ]:
df.to_csv("abc.csv",index=False)

In [7]:
students=pd.read_csv("students.csv")

In [8]:
students.head()

id_number               Name  Age Gender
0        204        James Smith   26      M
1        202    Maria Rodriguez   22      F
2        264        David Smith   24      M
3        136    Patricia Garcia   21      F
4        238  Jessica Hernandez   25      F

In [9]:
professor=pd.read_csv("professors.csv")
professor.head()

Prof_name  id_number Department
0     Thomas Smith        204        ECE
1  Margaret Garcia        264         EE
2    James Johnson        108        CSE
3   Richard Miller        238         ME
4   Margaret MOORE        136         CE

In [1]:
import pandas as pd
pd.concat([students,professor],ignore_index=True,axis=1)

NameError: name 'students' is not defined